# Generated by Django 5.1.2 on 2024-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
