# Generated by Django 5.1.2 on 2024-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('name', models.CharField(max_length=200, null=True)),
                ('team_intro', models.CharField(max_length=400, null=True)),
                ('team_members', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ourwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('Source_code', models.CharField(blank=True, max_length=200, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
