# Generated by Django 5.1.2 on 2024-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowmore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteams',
            name='team_intro',
        ),
        migrations.RemoveField(
            model_name='ourteams',
            name='team_members',
        ),
        migrations.AddField(
            model_name='ourteams',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
