# Generated by Django 5.1.2 on 2024-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowmore', '0002_remove_ourteams_team_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteams',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
