# Generated by Django 5.1.2 on 2024-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowmore', '0003_ourteams_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourwork',
            name='Source_code',
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='demo_link',
        ),
        migrations.AddField(
            model_name='ourwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
